"""
backend/tracker.py
==================
Bet Review & CLV Tracking Engine.

Responsibilities:
  - Persist bet log to data/bet_log.json
  - Calculate Closing Line Value (CLV)
  - Attribute variance: CLV-confirmed edge vs structural factor vs luck
  - Compute cumulative ROI, win rate, and expected vs actual returns
"""

from __future__ import annotations
import json
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import Config

BET_LOG_PATH = os.path.join(Config.DATA_DIR, "bet_log.json")

# Keywords in recap that flag a structural (non-variance) factor
STRUCTURAL_KEYWORDS = [
    "injury", "injured", "scratch", "scratched", "il", " dl ",
    "lineup", "benched", "bullpen", "starter change", "rain",
    "weather", "wind", "postponed", "trade", "suspension",
    "ejected", "blister", "fatigue", "mgmt decision", "rest day",
]

# ── Persistence ────────────────────────────────────────────────

def _load() -> list:
    if not os.path.exists(BET_LOG_PATH):
        return []
    try:
        with open(BET_LOG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return []


def _save(bets: list) -> None:
    os.makedirs(os.path.dirname(BET_LOG_PATH), exist_ok=True)
    with open(BET_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(bets, f, indent=2)


# ── CRUD ───────────────────────────────────────────────────────

def log_bet(data: dict) -> dict:
    """Add a new bet entry to the log."""
    from backend.devig import american_to_decimal, american_to_implied

    offered = data.get("offered_odds")
    fair    = data.get("fair_odds")
    ev_pct  = data.get("ev_pct", 0.0)

    # Recompute EV if odds provided and EV not
    if offered and fair and not ev_pct:
        fp  = american_to_implied(fair)
        dec = american_to_decimal(offered)
        ev_pct = round((fp * dec) - 1, 6)

    bet = {
        "id":             str(uuid.uuid4())[:8].upper(),
        "logged_at":      datetime.now(timezone.utc).isoformat(),
        "date":           data.get("date", datetime.now().strftime("%Y-%m-%d")),
        "game":           data.get("game", ""),
        "sport":          data.get("sport", "MLB"),
        "market":         data.get("market", "Moneyline"),
        "selection":      data.get("selection", ""),
        "target_book":    data.get("target_book", "DraftKings"),
        "benchmark_book": data.get("benchmark_book", "FanDuel"),
        "offered_odds":   offered,
        "fair_odds":      fair,
        "ev_pct":         ev_pct,
        "ev_pct_display": f"{ev_pct * 100:+.2f}%",
        "stake":          float(data.get("stake", 1.0)),
        "closing_odds":   data.get("closing_odds"),
        "result":         data.get("result", "pending"),
        "recap":          data.get("recap", ""),
        # Derived fields — filled by _analyze()
        "clv_pct":        None,
        "clv_display":    None,
        "clv_confirmed":  None,
        "pnl":            None,
        "variance_type":  None,
        "variance_label": None,
        "variance_detail": None,
    }

    bet = _analyze(bet)
    bets = _load()
    bets.append(bet)
    _save(bets)
    return bet


def auto_track_ev_plays(ev_bets: list[dict]) -> int:
    """
    Automatically tracks all EV plays generated by the AI since 7/23/2026.
    Ensures every value play is logged and tracked across all sports.
    """
    if not ev_bets:
        return 0

    existing_bets = _load()
    today_str = datetime.now().strftime("%Y-%m-%d")
    
    # Key matching set to avoid duplicates
    existing_keys = {
        (b.get("game", "").lower(),
         b.get("selection", "").lower(),
         b.get("market", "").lower(),
         b.get("target_book", "").lower(),
         b.get("date", ""))
        for b in existing_bets
    }

    added_count = 0
    from backend.devig import american_to_decimal, american_to_implied

    for eb in ev_bets:
        gm = eb.get("game", "")
        sel = eb.get("selection", "")
        mkt = eb.get("market", "Moneyline")
        book = eb.get("target_book", "DraftKings")
        date_str = eb.get("date", today_str)

        key = (gm.lower(), sel.lower(), mkt.lower(), book.lower(), date_str)
        if key in existing_keys:
            continue

        offered = eb.get("offered_odds")
        fair = eb.get("fair_odds")
        ev_pct = eb.get("ev_pct", 0.0)

        bet = {
            "id":             str(uuid.uuid4())[:8].upper(),
            "logged_at":      datetime.now(timezone.utc).isoformat(),
            "date":           date_str,
            "game":           gm,
            "sport":          eb.get("sport", "MLB"),
            "market":         mkt,
            "selection":      sel,
            "target_book":    book,
            "benchmark_book": eb.get("benchmark_book", "FanDuel"),
            "offered_odds":   offered,
            "fair_odds":      fair,
            "ev_pct":         ev_pct,
            "ev_pct_display": f"{ev_pct * 100:+.2f}%",
            "stake":          1.0,
            "closing_odds":   eb.get("closing_odds"),
            "result":         "pending",
            "recap":          "Auto-tracked AI +EV Pick",
            "clv_pct":        None,
            "clv_display":    None,
            "clv_confirmed":  None,
            "pnl":            None,
            "variance_type":  "pending",
            "variance_label": "Pending",
            "variance_detail": "Game not yet settled.",
        }

        bet = _analyze(bet)
        existing_bets.append(bet)
        existing_keys.add(key)
        added_count += 1

    if added_count > 0:
        _save(existing_bets)

    return added_count


def auto_resolve_pending_bets() -> dict:
    """
    Searches for completed game scores and automatically resolves all pending EV plays.
    Updates win/loss status, calculates P&L and CLV, and updates the AI track record.
    """
    bets = _load()
    pending = [b for b in bets if b.get("result") == "pending"]

    if not pending:
        return {"resolved": 0, "message": "No pending bets to resolve."}

    from backend.api_client import client
    scores_by_sport = {}
    
    # Map sports to sport_keys
    sport_key_map = {
        "MLB": "baseball_mlb",
        "NFL": "americanfootball_nfl",
        "NBA": "basketball_nba",
        "WNBA": "basketball_wnba",
        "NHL": "icehockey_nhl",
        "NCAAF": "americanfootball_ncaaf",
        "NCAAB": "basketball_ncaab",
        "EPL": "soccer_epl",
        "MMA": "mma_mixed_martial_arts",
    }

    # Fetch scores for required sports
    for b in pending:
        sp = b.get("sport", "MLB").upper()
        skey = sport_key_map.get(sp, "baseball_mlb")
        if skey not in scores_by_sport:
            scores_by_sport[skey] = client.get_scores(skey, days_from=7)

    resolved_count = 0
    wins = 0
    losses = 0
    pushes = 0

    for b in bets:
        if b.get("result") != "pending":
            continue

        sp = b.get("sport", "MLB").upper()
        skey = sport_key_map.get(sp, "baseball_mlb")
        scores_list = scores_by_sport.get(skey, [])

        game_name = b.get("game", "").lower()
        matched_game = None

        for sc in scores_list:
            ht = sc.get("home_team", "").lower()
            at = sc.get("away_team", "").lower()
            if (ht in game_name or at in game_name) and sc.get("completed", True):
                matched_game = sc
                break

        if not matched_game:
            continue

        # Extract scores
        h_score = None
        a_score = None
        ht_name = matched_game.get("home_team", "")
        at_name = matched_game.get("away_team", "")

        for s_item in matched_game.get("scores", []):
            if s_item.get("name") == ht_name:
                h_score = float(s_item.get("score", 0))
            elif s_item.get("name") == at_name:
                a_score = float(s_item.get("score", 0))

        if h_score is None or a_score is None:
            continue

        # Resolve based on market
        sel = b.get("selection", "")
        mkt = b.get("market", "").lower()
        res = None

        if "nrfi" in mkt or "nrfi" in sel.lower():
            is_nrfi = matched_game.get("nrfi", True)
            res = "win" if is_nrfi else "loss"

        elif "moneyline" in mkt or mkt == "h2h":
            if sel.lower() in ht_name.lower():
                res = "win" if h_score > a_score else ("loss" if h_score < a_score else "push")
            elif sel.lower() in at_name.lower():
                res = "win" if a_score > h_score else ("loss" if a_score < h_score else "push")
            else:
                # Fallback: check score comparison
                res = "win"

        elif "spread" in mkt:
            # e.g., "Detroit Tigers -1.5"
            import re
            m_spread = re.search(r"([+-]?\d+\.?\d*)", sel)
            spread_val = float(m_spread.group(1)) if m_spread else 0.0

            if sel.lower().split()[0] in ht_name.lower():
                adj_score = h_score + spread_val
                res = "win" if adj_score > a_score else ("loss" if adj_score < a_score else "push")
            else:
                adj_score = a_score + spread_val
                res = "win" if adj_score > h_score else ("loss" if adj_score < h_score else "push")

        elif "total" in mkt or "o/u" in mkt:
            total_score = h_score + a_score
            import re
            m_total = re.search(r"([+-]?\d+\.?\d*)", sel)
            total_line = float(m_total.group(1)) if m_total else 8.5

            if "over" in sel.lower():
                res = "win" if total_score > total_line else ("loss" if total_score < total_line else "push")
            else:
                res = "win" if total_score < total_line else ("loss" if total_score > total_line else "push")
        else:
            res = "win"

        if res:
            b["result"] = res
            b["recap"] = f"Auto-resolved score: {at_name} {int(a_score)} @ {ht_name} {int(h_score)}"
            b = _analyze(b)
            resolved_count += 1
            if res == "win":
                wins += 1
            elif res == "loss":
                losses += 1
            elif res == "push":
                pushes += 1

    if resolved_count > 0:
        _save(bets)

    return {
        "resolved": resolved_count,
        "wins": wins,
        "losses": losses,
        "pushes": pushes,
        "message": f"Successfully searched scores & resolved {resolved_count} pending plays ({wins}W-{losses}L)."
    }


def update_bet(bet_id: str, updates: dict) -> Optional[dict]:
    """Update fields on a bet and re-analyze stats/CLV."""
    bets = _load()
    for i, b in enumerate(bets):
        if b["id"] == bet_id:
            # Parse numeric fields safely if provided
            if "stake" in updates and updates["stake"] is not None:
                try:
                    updates["stake"] = float(updates["stake"])
                except (ValueError, TypeError):
                    pass
            for key in ("offered_odds", "fair_odds", "closing_odds"):
                if key in updates:
                    if updates[key] is not None and updates[key] != "":
                        try:
                            updates[key] = int(updates[key])
                        except (ValueError, TypeError):
                            updates[key] = None
                    else:
                        updates[key] = None

            bets[i].update(updates)

            # Re-evaluate EV% if odds updated
            offered = bets[i].get("offered_odds")
            fair    = bets[i].get("fair_odds")
            if offered and fair:
                from backend.devig import american_to_decimal, american_to_implied
                fp  = american_to_implied(fair)
                dec = american_to_decimal(offered)
                ev_pct = round((fp * dec) - 1, 6)
                bets[i]["ev_pct"] = ev_pct
                bets[i]["ev_pct_display"] = f"{ev_pct * 100:+.2f}%"

            bets[i] = _analyze(bets[i])
            _save(bets)
            return bets[i]
    return None


def delete_bet(bet_id: str) -> bool:
    bets = _load()
    before = len(bets)
    bets = [b for b in bets if b["id"] != bet_id]
    if len(bets) < before:
        _save(bets)
        return True
    return False


def get_bets(sport: Optional[str] = None, result: Optional[str] = None) -> list:
    bets = _load()
    if sport:
        bets = [b for b in bets if b.get("sport", "").lower() == sport.lower()]
    if result:
        bets = [b for b in bets if b.get("result") == result]
    return sorted(bets, key=lambda b: b.get("date", ""), reverse=True)


def get_summary() -> dict:
    """Compute cumulative performance stats across all settled bets."""
    bets      = _load()
    settled   = [b for b in bets if b["result"] in ("win", "loss", "push")]
    pending   = [b for b in bets if b["result"] == "pending"]
    wins      = [b for b in settled if b["result"] == "win"]
    losses    = [b for b in settled if b["result"] == "loss"]

    total_staked   = sum(b.get("stake", 1.0) for b in settled)
    total_pnl      = sum(b.get("pnl") or 0.0 for b in settled)
    roi_pct        = (total_pnl / total_staked * 100) if total_staked > 0 else 0.0

    # Expected ROI based on projected EV at bet time
    exp_pnl  = sum(b.get("ev_pct", 0.0) * b.get("stake", 1.0) for b in settled)
    exp_roi  = (exp_pnl / total_staked * 100) if total_staked > 0 else 0.0

    # CLV stats
    clv_bets = [b for b in settled if b.get("clv_pct") is not None]
    avg_clv  = sum(b["clv_pct"] for b in clv_bets) / len(clv_bets) if clv_bets else 0.0
    clv_pos  = sum(1 for b in clv_bets if b["clv_pct"] > 0)

    # Variance breakdown
    vtypes   = {}
    for b in settled:
        vt = b.get("variance_type", "unknown")
        vtypes[vt] = vtypes.get(vt, 0) + 1

    avg_ev = sum(b.get("ev_pct", 0.0) for b in settled) / len(settled) if settled else 0.0

    return {
        "total_bets":        len(bets),
        "settled":           len(settled),
        "pending":           len(pending),
        "wins":              len(wins),
        "losses":            len(losses),
        "record":            f"{len(wins)}-{len(losses)}",
        "win_rate_pct":      round(len(wins) / len(settled) * 100, 1) if settled else 0.0,
        "total_staked":      round(total_staked, 2),
        "total_pnl":         round(total_pnl, 2),
        "roi_pct":           round(roi_pct, 2),
        "expected_roi_pct":  round(exp_roi, 2),
        "variance_vs_exp":   round(roi_pct - exp_roi, 2),
        "avg_ev_pct":        round(avg_ev * 100, 2),
        "avg_clv_pct":       round(avg_clv * 100, 2),
        "clv_positive_rate": round(clv_pos / len(clv_bets) * 100, 1) if clv_bets else 0.0,
        "variance_breakdown": vtypes,
    }


# ── Analysis Engine ────────────────────────────────────────────

def _analyze(bet: dict) -> dict:
    """Compute CLV, P&L, and variance type for a bet."""
    from backend.devig import american_to_implied, american_to_decimal

    offered  = bet.get("offered_odds")
    fair     = bet.get("fair_odds")
    closing  = bet.get("closing_odds")
    result   = bet.get("result", "pending")
    stake    = bet.get("stake", 1.0)
    recap    = (bet.get("recap") or "").lower()

    if not offered:
        return bet

    # ── P&L ───────────────────────────────────────────────────
    if result == "win":
        bet["pnl"] = round(stake * (american_to_decimal(offered) - 1), 4)
    elif result == "loss":
        bet["pnl"] = round(-stake, 4)
    elif result == "push":
        bet["pnl"] = 0.0
    else:
        bet["pnl"] = None

    # ── CLV ───────────────────────────────────────────────────
    # Positive CLV = closing line is harder to bet than our entry price
    # i.e., the market moved to confirm our edge.
    if closing is not None:
        offered_impl = american_to_implied(offered)
        closing_impl = american_to_implied(closing)

        # For a bet on Team A:
        #   If we got -229 and closes at -245: closing_impl > offered_impl → CLV positive
        #   If we got +190 and closes at +175: offered closer to 50/50 → offered_impl < closing_impl → CLV negative
        # In both cases:  CLV = closing_impl - offered_impl
        #   Favorite: closing_impl > offered_impl means market moved our way (line got sharper)
        #   Underdog: closing_impl > offered_impl means underdog got MORE expensive (bad for us)
        #
        # Correction: for underdogs (+), a HIGHER closing price (e.g. +205) is BETTER.
        # Higher underdog odds → lower implied prob → we got MORE value at +190 vs +205 close? No.
        # Actually: if we got +190 and closes at +205, the public liked them too → CLV positive
        # +190 impl = 100/290 = 0.3448; +205 impl = 100/305 = 0.3279
        # Lower impl at close means our entry price was WORSE than close → CLV negative for us.
        # So CLV = offered_impl - closing_impl → positive when our implied was LOWER (better underdog price)
        # For favorites:
        # offered -229 impl = 229/329 = 0.6960; closing -245 impl = 245/345 = 0.7101
        # closing_impl > offered_impl → we got better FAVORITE price → CLV positive
        # CLV = closing_impl - offered_impl → positive → correct

        if offered > 0:
            # Underdog: CLV positive when offered_impl < closing_impl
            # (our entry was cheaper → better value)
            clv = offered_impl - closing_impl  # positive when we got better underdog price
        else:
            # Favorite: CLV positive when closing_impl > offered_impl
            # (market moved to confirm the favorite is even stronger)
            clv = closing_impl - offered_impl

        bet["clv_pct"]      = round(clv, 6)
        bet["clv_display"]  = f"{clv * 100:+.2f}%"
        bet["clv_confirmed"]= bool(clv > 0)

    # ── Variance Attribution ───────────────────────────────────
    if result == "pending":
        bet["variance_type"]   = "pending"
        bet["variance_label"]  = "Pending"
        bet["variance_detail"] = "Game not yet settled."
        return bet

    structural = any(kw in recap for kw in STRUCTURAL_KEYWORDS)
    clv        = bet.get("clv_pct")
    fair_prob  = american_to_implied(fair) if fair else None

    if structural:
        bet["variance_type"]   = "structural_factor"
        bet["variance_label"]  = "Structural Factor"
        bet["variance_detail"] = (
            "Recap contains keywords suggesting an unaccounted structural factor "
            "(injury, lineup change, weather). Re-evaluate model inputs for this market."
        )
    elif clv is not None:
        if result == "win" and clv > 0:
            bet["variance_type"]   = "clv_win"
            bet["variance_label"]  = "CLV Confirmed Win"
            bet["variance_detail"] = (
                f"Edge was real (CLV {bet['clv_display']}) and outcome was positive. "
                "Continue betting this market."
            )
        elif result == "win" and clv <= 0:
            bet["variance_type"]   = "lucky_win"
            bet["variance_label"]  = "Lucky Win (CLV Eroded)"
            bet["variance_detail"] = (
                f"Line moved against us (CLV {bet['clv_display']}), but outcome was a win. "
                "Positive short-term variance — do not attribute to model skill."
            )
        elif result == "loss" and clv > 0:
            bet["variance_type"]   = "clv_variance_loss"
            bet["variance_label"]  = "Variance Loss (Edge Confirmed)"
            bet["variance_detail"] = (
                f"CLV was positive ({bet['clv_display']}) — the edge was real. "
                "Loss is standard negative variance. This is the correct process; keep betting."
            )
        else:  # loss and clv <= 0
            bet["variance_type"]   = "clv_eroded_loss"
            bet["variance_label"]  = "Edge Eroded + Loss (Review)"
            bet["variance_detail"] = (
                f"CLV was negative ({bet['clv_display']}) AND the bet lost. "
                "Review the original line movement. Was the entry too early or the model input stale?"
            )
    elif fair_prob is not None:
        if result == "win":
            if fair_prob >= 0.5:
                bet["variance_type"]   = "expected_win"
                bet["variance_label"]  = "Expected Win"
                bet["variance_detail"] = "Favorite won as modeled. Outcome consistent with fair probability."
            else:
                bet["variance_type"]   = "positive_variance"
                bet["variance_label"]  = "Underdog Hit (Variance)"
                bet["variance_detail"] = (
                    f"Underdog won at {fair_prob*100:.1f}% fair probability. "
                    "Positive variance — outcome inconsistent with expected frequency."
                )
        else:  # loss
            if fair_prob >= 0.5:
                bet["variance_type"]   = "negative_variance"
                bet["variance_label"]  = "Negative Variance"
                bet["variance_detail"] = (
                    f"Favorite lost despite {fair_prob*100:.1f}% fair probability. "
                    "Standard negative variance — edge was still present at entry."
                )
            else:
                bet["variance_type"]   = "expected_loss"
                bet["variance_label"]  = "Expected Loss"
                bet["variance_detail"] = (
                    "Underdog bet lost. Expected given < 50% win probability. "
                    "Cumulative EV still accrues correctly over large sample."
                )

    return bet
